import AppBar from "@/app/components/AppBar";
import "./globals.css";
import Providers from "@/app/components/Providers";

export const metadata = {
  title: "RoseGold Assignment Login",
  description: "Generated by Pataratanan",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout(props: Props) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AppBar />
          {props.children}
        </Providers>
      </body>
    </html>
  );
}